CREATE DATABASE CALCULATION;

USE CALCULATION;

CREATE TABLE ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD TEXT(100) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_ROLE (
  USER_ID BIGINT(20) NOT NULL,
  ROLE_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO ROLE(NAME) VALUES('ROLE_ADMIN');
INSERT INTO ROLE(NAME) VALUES('ROLE_USER');

INSERT INTO USER(NAME, USERNAME, EMAIL, PASSWORD) VALUES('admin', 'admin', 'admin@gmail.com', '$2a$10$j9LW3hic3F5s1soqsRqgX.jbCA631SmxI.tdyhS0SUPeoglbpHihK');
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(1, 1);


CREATE TABLE HISTORY (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE TIMESTAMP NOT NULL,
  CREATED_BY BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CREATED_BY) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

